##########
# COLORS #
##########

include ~/.config/kitty/themes/mocha.conf

###########
# OPACITY #
###########

background_opacity 0.55

########
# FONT #
########

font_family Hack Nerd Font Mono
font_size   13.0

#########
# SHELL #
#########

shell /usr/bin/zsh
confirm_os_window_close 0

##########
# CURSOR #
##########
cursor_trail 4

cursor_animate yes
cursor_animate_speed 0.85
