# ~/.config/hypr/hyprpaper.conf

# Enable IPC so hyprctl commands work
ipc = true
splash = false

# Preload your wallpaper for faster switching
preload = /home/elliot/Wallpapers/nature-valley-2.jpg


# Set wallpaper on external monitor
wallpaper {
    monitor = DP-2
    path    = /home/elliot/Wallpapers/nature-valley-2.jpg
}
