#################
### AUTOSTART ###
#################

# Autostart necessary processes (like notifications daemons, status bars, etc.)

exec-once = qs & dunst & elephant & swaysod-server &
exec-once = awww-daemon
exec-once = awww restore


